version: 1
disable_existing_loggers: false

formatters:
  verbose:
    format: '%(levelname)s %(asctime)s %(module)s %(message)s'

handlers:
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: verbose

loggers:
  auth_server:
    level: INFO
    handlers: [console]
  papermerge.search.tasks:
    level: INFO
    handlers: [console]
    propagate: no
  s3worker:
    level: DEBUG  # Set to DEBUG for maximum visibility
    handlers: [console]
    propagate: no
  s3worker.tasks:
    level: DEBUG
    handlers: [console]
    propagate: no
  s3worker.client:
    level: DEBUG
    handlers: [console]
    propagate: no
  celery:
    level: INFO
    handlers: [console]
    propagate: no
